age = int(input("please tell me your age:"))
print(f"you are currently {age} year old")
print(f"In 10 years, you will be {age+10} year old")
print(f"In 20 years, you will be {age+20} year old")
print(f"In 30 years, you will be {age+30} year old")